name = "DocuAPI"
license = "Apache-2.0"
licenselink = "https://github.com/bep/docuapi/blob/master/LICENSE.md"
description = "Beautiful documentation for your API."
homepage = "https://github.com/bep/docuapi"
tags = ["Documentation", "API", "Docs", "Responsive", "Multilingual"]
features = ["Documentation", "Multilingual"]
min_version = 0.17

[author]
  name = "Bj√∏rn Erik Pedersen"
  homepage = "http://bep.is"

[original]
  name = "Slate"
  homepage = "https://github.com/lord/slate"
  repo = "https://github.com/lord/slate"
